### ISSUE TITLE
Suggestion to improve the readme - mention the config file name

### ISSUE THREAD

**Issue by oren** [boxdot/gurk-rs#10]
The readme mention a config file but doesn't specific the name of the file. Is this gurk.toml?
https://github.com/boxdot/gurk-rs/blob/master/src/config.rs#L46

If that's the case it might be useful to mention it so people who are not familiar with rust will be able to use it.

Thanks!

**Comment by boxdot** [comment]
Thank you for the proposal. I indeed forgot to add the name.
