### ISSUE TITLE
cannot link device 

### ISSUE THREAD

**Issue by greweln** [boxdot/gurk-rs#101]
I'm scaning the barcode with both Samsung and Apple phone but getting either "network error", ""no device found", "device approuved"(but doesn't appear under linked devices).
Any advice?

**Comment by drdloc** [comment]
Can confirm something similar is happening to me on initial start up as well.

I scan the bar code and the following error gets sent to command line:
```
Linking new device with device name: gurk@IceCube
Error: libsignal-service sending error: Unexpected response: HTTP 404

Caused by:
    0: Unexpected response: HTTP 404
    1: Unexpected response: HTTP 404
```

I noticed that afterwards the device is linked with unnamed device but then no json file or config is created.

**Comment by boxdot** [comment]
I am afraid this problem might be either in `presage` or even deeper in https://github.com/whisperfish/libsignal-service-rs. Maybe you could try to link with `RUST_LOG=debug` exported. This might show a better log for tracking the issue.

**Comment by corporealshift** [comment]
I'm getting the same error. I tried with RUST_LOG=debug and didn't have any better messages come through =(
```
> RUST_LOG=debug gurk
Linking new device with device name: gurk@Kyle's-MacBook-Pro
Error: libsignal-service sending error: Unexpected response: HTTP 404

Caused by:
    0: Unexpected response: HTTP 404
    1: Unexpected response: HTTP 404
    ```

**Comment by gferon** [comment]
Should be easy to reproduce, I'll give it a look ASAP.

**Comment by gferon** [comment]
@chaseadam sorry, you're right! once #105 it should work. (ah, the joy of dependencies across multiple git repositories 😄)
