### ISSUE TITLE
Unable to detect Shift+Enter

### ISSUE THREAD

**Issue by Sup3Legacy** [boxdot/gurk-rs#108]
I'm currently looking into implementing the multi-line feature using the `Shift + Enter` keybinding. However it seems the event handling implementation is not able to capture it. Pressing this binding only yields

```rust
KeyEvent { code: Enter, modifiers: NONE }
```

i.e. the `SHIFT` modifier is not detected.

**Comment by boxdot** [comment]
I remember reading that Shift+Enter is not supported by many terminals and therefore the backend does not support it. I implemnted switched the multiline mode btw. via Alt+Enter.
