### ISSUE TITLE
Rate limiting on too many receipts

### ISSUE THREAD

**Issue by boxdot** [boxdot/gurk-rs#115]
We get rate limited since we are sending to many receipts back. 

Atm, this is done in the UI component. We should move it out of there.

**Comment by Sup3Legacy** [comment]
This is really an issue. Although I conducted tests without any problem, I ran into an issue a few days ago where all the conversations and groups with a particular contact got totally frozen (meaning neither of us can successfully send messages in these conversations for some reason). I'm not sure as to what extent this issue if linked with the rate limitation though.

I would say an issue is that all messages received before the feature had been added all have the `Receipt::Nothing` flag thus making the client catch on all these messages in a very short period of time.

**Comment by Sup3Legacy** [comment]
Okay I finally got the (very stupid) bug : the piece of code in `ui.rs` was calling the `SignalManager::send_receipts` even with an empty `Vec` of `timestamps`, thus spamming messages at 60mps...

**Comment by boxdot** [comment]
Maybe we can move it out of UI. Seem to be a wrong place for doing some work. We could have some data structure, like a set, which worked on each iteration of the main loop. After an item processed in the set, it can be removed and does not have to be touched again. In the case of receipts, we could hold a set of unread messages.

**Comment by Sup3Legacy** [comment]
The main issue is corrected on my branch.

I'll spend some time thinking about how to redo the whole receipt workflow.

**Comment by Sup3Legacy** [comment]
Should be addressed in #116!
