### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Sup3Legacy** [boxdot/gurk-rs#117]
As `gurk` now has some features that some users may wish to disable (especially regarding the message receipts), I think some sort of settings panel to toggle them would be a great addition. If approved, I can look into implementing this.

**Comment by boxdot** [comment]
I personally like to keep it simple and do configuration in a config file. E.g. alacritty or sublime text do it in that way. The users of gurk are most likely power users, since they use it in a terminal. Does it make sense?

What do you think about adding the receipt setting to the config file?

**Comment by Sup3Legacy** [comment]
You have a good point there. Would also be simpler to do it that way!
