### ISSUE TITLE
No device found error

### ISSUE THREAD

**Issue by boxdot** [boxdot/gurk-rs#118]
A user reports when starting on a fresh machine with version 0.2.2, after scanning the QR code 'No device found error' appears on the android app and gurk fails with 'no provisioning message received'.

**Comment by MrP01** [comment]
Hello!

I experience the following (freshly installed): After starting gurk, it instructs me to scan the QR-Code.

`Linking new device with device name: gurk@bu201la`

After doing so on Signal, it asks me to conform as follows:
![image](https://user-images.githubusercontent.com/12398709/147392238-bf191832-d0d1-4b5d-9424-75b0e8c5f189.png)

I confirm and on the command line, it outputs the following error message, and exits:

```
Error: failed to get the user profile

Caused by:
    0: libsignal-service error: Error decoding JSON response: missing field `name` at line 1 column 299
    1: Error decoding JSON response: missing field `name` at line 1 column 299
```

What I found interesting: when visiting my linked devices, the newly connected device doesn't have a name ("Unnamed device").
![image](https://user-images.githubusercontent.com/12398709/147392260-59639455-837c-4949-b878-454e496ab3fc.png)

Hope this helps! Thanks :)

**Comment by itdaniher** [comment]
Feels familiar... I think we ran into this with Auxin and this was our fix:

https://github.com/mobilecoinofficial/auxin/commit/1275fe4cafb542b0473c394f3326dd48ed012a78

**Comment by technillogue** [comment]
Hm, it looks like this is already optional: https://github.com/whisperfish/libsignal-service-rs/blob/f1afccd13d110cb4e80f5f330a0384b9af2b12c6/libsignal-service/src/push_service.rs#L249 , though I'm not sure where the json gets turned into a SignalServiceProfile

**Comment by gferon** [comment]
For now, [this will fix the bug](https://github.com/whisperfish/libsignal-service-rs/pull/120), although there are issues with the device name and fields in the profile are empty
