### ISSUE TITLE
Notifications bumb direct messages channel up

### ISSUE THREAD

**Issue by boxdot** [boxdot/gurk-rs#127]
Looks like reading notification push the direct message channels up even there is no message there.

**Comment by cxloe** [comment]
this is especially bad with large groups. seems like all the delivery notifications pop up in the sidebar when sending messages

**Comment by Sup3Legacy** [comment]
What do you mean precisely? I failed to reproduce the issue as I understand it.

**Comment by boxdot** [comment]
When a person writes in a group, there are incoming notification messages from this person and those bubble up the channel with this person.

I have a fix for that. Will upload soon.
