### ISSUE TITLE
Bug: infinite loop while skkiping words on input box

### ISSUE THREAD

**Issue by mucinoab** [boxdot/gurk-rs#129]
Tested on latest [master](https://github.com/boxdot/gurk-rs/tree/22be6e4256f44c083faef1697a2160d2a01eed7e).
Steps to reproduce:
- Write two words on the input box, the second one must contain a multi-byte character, like an emoji or an accented character.
- Put the cursor back at the beginning.
- Move forward two words with Ctrl + Right

At this point the UI is frozen and consuming 100% cpu.

**Comment by boxdot** [comment]
Thank you for the bug report. I am reworking the text input navigation atm. I should have a patch and fix for that soon.
