### ISSUE TITLE
Latest pull of gurk crashes, creates weird problem with input to terminal

### ISSUE THREAD

**Issue by cxloe** [boxdot/gurk-rs#132]
Looks like it's crashing about here:

[2022-02-08T21:46:10.648963140-05:00 ERROR log_panics] thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/app.rs:1145

![image](https://user-images.githubusercontent.com/77425619/153112420-d6b45d5f-c5ec-47f5-8313-f41b6cf57934.png)

**Comment by cxloe** [comment]
Whenever i move my mouse, more text shows up in the terminal

**Comment by Sup3Legacy** [comment]
You probably received a typing notification from a group that was not yet, I'll try and fix that.

Regarding the weird text in the terminal, the same also happens to me.

**Comment by boxdot** [comment]
@cxloe Are using the version from master?

**Comment by cxloe** [comment]
yep! @boxdot
