### ISSUE TITLE
gurk-rs has been packaged for NixOS

### ISSUE THREAD

**Issue by devhell** [boxdot/gurk-rs#138]
Hi!

I've [packaged](https://github.com/NixOS/nixpkgs/commit/54c4e7786be361e68c2759608320ec0c7ad15156) your wonderful project for [NixOS](https://nixos.org/). Thank you for this, it's much nicer to interact with Signal in a terminal than the native client. I'm looking forward to seeing improvements to `gurk` :smiley: 

Thanks again, prost! :beers:

**Comment by Sup3Legacy** [comment]
@devhell Thanks for that, we're now at 2 packages (AFAIK)!

@boxdot wanna add a mention in the README to give this package more visibility? Maybe you can do that in one of your current PRs.

**Comment by boxdot** [comment]
All current PRs are merged. Feel free to open a new one.

**Comment by devhell** [comment]
I'll try to get a PR going with info regarding NixOS asap.
