### ISSUE TITLE
Reactions are broken

### ISSUE THREAD

**Issue by Sup3Legacy** [boxdot/gurk-rs#147]
Seems that message reactions are currently broken. When adding reactions using `gurk`, they do appear locally but I do not see them on my other Signal clients, nor the other way around.

There's also an issue with the message selection: reactions sent from `gurk` do appear in `gurk`, as stated, but sometimes on the wrong message. 

Not quite sure where these issues originate.

**Comment by boxdot** [comment]
Fixed in #331
