### ISSUE TITLE
dbus exception: Cannot resolve session bus address

### ISSUE THREAD

**Issue by lattera** [boxdot/gurk-rs#15]
Running in a tmux session on HardenedBSD. DBus is enabled. Screenshot attached.

![2020-08-03_gurk-01](https://user-images.githubusercontent.com/573797/89187238-8a42e900-d58c-11ea-9394-97a45e072ec2.png)

**Comment by boxdot** [comment]
Thank you for reporting the issue. I really need to add a custom panic handler which prints the text properly.

Looks like this is an error coming from https://github.com/AsamK/signal-cli. Not sure I can solve it. There is an ambitious plan to replace signal-cli by a native rust backend, which would remove these kind of issues automatically.

**Comment by dnapier** [comment]
Got the same issue. Built on archlinux:latest without AUR. Looking forward to when this works!

**Comment by boxdot** [comment]
In release 0.2.0, signal-cli was removed. Now, the official Signal client crate is used. This solves this problem. 

Also a custom panic hood was added which uses `log` to output panics. Logging can be enabled with the `-v` flag.
