### ISSUE TITLE
QR Code Should Render in the Terminal

### ISSUE THREAD

**Issue by knpwrs** [boxdot/gurk-rs#150]
As demonstrated by https://qrenco.de/, it is possible to render QR codes in the terminal. For instance:

```
curl https://qrenco.de/https://signal.org
```

<img width="308" alt="image" src="https://user-images.githubusercontent.com/174864/164144327-0f5917c1-acf5-4d58-a5ba-9826b0be074a.png">

I think this would provide a much better UX than opening a system-native image viewer.

**Comment by jayrahdevore** [comment]
This appears to have been addressed in #128
