### ISSUE TITLE
Own messages from other devices not visible in groups

### ISSUE THREAD

**Issue by phil-bell** [boxdot/gurk-rs#171]
Seems like your own messages from another device don't show up in the group chats on gurk.

Method to reproduce:
1. create or view a group on gurk
2. send a message to the group from your phone
3. message is not visible in gurk

The reverse of the above does work, so messages sent from gurk appear on your phone fine.
It also looks like this only happens in groups and not direct messages.

**Comment by boxdot** [comment]
Could you please verify if #172 fixes your issue? From you description, it seems to be related but slightly different.
