### ISSUE TITLE
Configurable notifications

### ISSUE THREAD

**Issue by rakoo** [boxdot/gurk-rs#188]
Hi there, thanks for your project it's probably the best TUI I've ever used for an IM !

In gurk notifications are working out of the box, but I don't want notifications, I want to read messages when I want only. Is there a way to deactivate them ?

Edit: ideally, gurk would write a magic file with the number of unread messages, and I would probe that file with my notification bar and only display something that tells me "there is some new stuff to read"

**Comment by boxdot** [comment]
I added a configuration flag `notifications = false  # default value true` to gurk's config in #192.

About magic file: W could add a `gurkctl` utility, which would provide a command to read out the number of unread message from a running instance of gurk. Maybe, we can think of other commands like marking all unread messages as read. Not sure though, whether such a tool would be useful.

**Comment by rakoo** [comment]
Thank you very much !

Regarding the utility, it might be a departure from the goal of gurk which is to provide a TUI. There is signal-cli that provides CLI capabilities, it's probably best to not make one big thing that does everything.

I leave the issue open if there is a need for discussion, but feel free to close if you feel like it :)
