### ISSUE TITLE
Error sending request

### ISSUE THREAD

**Issue by Phantop** [boxdot/gurk-rs#189]
Trying to run the latest release on Linux (Solus) gives me this error:

```
Error: libsignal-service sending error: Error sending request: error trying to connect: invalid certificate: UnknownIssuer

Caused by:
    0: Error sending request: error trying to connect: invalid certificate: UnknownIssuer
    1: Error sending request: error trying to connect: invalid certificate: UnknownIssuer
```

**Comment by ephemer4l** [comment]
Same here running on Gentoo.

**Comment by gferon** [comment]
Sorry for that, the CA certificate we embed in `libsignal-service-rs` wasn't correct and we fixed it this morning. I'll open a PR for `gurk` right away.

**Comment by gferon** [comment]
@Phantop / @ephemer4l if you want to try the patch out before #190 is merged (and if you have Rust installed), you can run:

`cargo install --git https://github.com/boxdot/gurk-rs --rev 77afa89e866f357178cf03b23b96d8ead1ed6f35 --locked --force gurk`

**Comment by Tachi107** [comment]
Hi, could you please tag a new point release? This is a fairly severe issue, making gurk unusable; also, not everybody has rustc/cargo installed on their own system.

Thanks!

**Comment by boxdot** [comment]
> Edit: it'd be nice if the CI jobs would allow users to download build artefacts, so that they could easily try out the latest master

I guess it is a good idea to add a nightly job which also produces a dist release (see #195)
