### ISSUE TITLE
Lost messages

### ISSUE THREAD

**Issue by boxdot** [boxdot/gurk-rs#197]
Some messages are lost by presage:

```
2022-11-01T20:29:20.068435Z ERROR presage::manager: Error opening envelope: SignalProtocolError(InvalidMessage(SenderKey, "unexpected message type for sealed_sender_decrypt")), message will be skipped!
```

Usually, I see this for group messages.

**Comment by boxdot** [comment]
Cf.  [wispherfish/presage](https://github.com/whisperfish/presage/issues/79)

**Comment by gferon** [comment]
JFYI, these messages don't seem to be very important as of today, and it's okay that they're skipped.

**Comment by boxdot** [comment]
Thank you for investigating. I will dig in into the `on_message` handler. Maybe we loose messages there.

**Comment by gferon** [comment]
The lost messages can be due do missing sessions or `InvalidSignedPreKey` which is another bug I've seen in the wild.
