### ISSUE TITLE
Feature request: copy to system clipboard from selected message

### ISSUE THREAD

**Issue by kiil** [boxdot/gurk-rs#206]
Hi,

I often use the 'note to self' in Signal to send quick "on the road" notes from my mobile, and then later open them in front of my computer at home and add them to my documents.

Currently I believe there is no way to copy from a selected message in gurk to the system clipboard.

Is that a feature you would consider implementing?

Thanks for a nice client :)

**Comment by boxdot** [comment]
We have already a way to select a mesage with Alt+Up/Down. On Enter, if there is a link in the message, we open the link in the default browser. Now, we need another shortcut for copy the contents into the clipboard. Any ideas? 

Unfortunately, clicking on the mesage for selecting it is not yet implemented. This might be also useful for this feature.

**Comment by kiil** [comment]
> Now, we need another shortcut for copy the contents into the clipboard. Any ideas?

If possible, `ctrl+enter`

to copy the contens of the selected message to the clipboard.

> clicking on the mesage for selecting it is not yet implemented

It is already possible to select the message with the scroll wheel on the mouse 👍

**Comment by boxdot** [comment]
After checking out several clipboard crates, it looks like arboard is the best (other have conflicting requirements on X11 and Wayland, and sometimes need a window). However, CTRL + Enter does not work in terminals. So we need to come up with a different binding.

**Comment by kiil** [comment]
Thanks for investigating this :)

> However, CTRL + Enter does not work in terminals. So we need to come up with a different binding.

How about ctrl-y for yank?

**Comment by boxdot** [comment]
Implemented for text messages with `alt+y`

**Comment by kiil** [comment]
Thanks for this :)
