### ISSUE TITLE
Gurk seems to crash shortly after startup

### ISSUE THREAD

**Issue by josephkerkhof** [boxdot/gurk-rs#223]
Shortly after starting gurk, it hard crashes (quits). When I run `gurk -v` and check the log there is this error at the end of the file:

```
2023-06-02T01:24:42.502985Z ERROR panic: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/signal/impl.rs:55
```

I see this error a few other times through the whole log file. I'm not exactly sure what's going on. I just set this up yesterday and it worked fine. I'm happy to help provide any other info to debug this.

**Comment by boxdot** [comment]
Looks like we panic when the group is not yet known. In https://github.com/boxdot/gurk-rs/pull/224, we now just log an error and do not panic anymore.

**Comment by josephkerkhof** [comment]
I tried that but am now having a different problem with my account getting unlinked. I'm not able to confirm that PR fixed this issue. :(

**Comment by josephkerkhof** [comment]
This issue is solved when installing from github.
