### ISSUE TITLE
Issue in put_char for chars like "é"

### ISSUE THREAD

**Issue by AmarOk1412** [boxdot/gurk-rs#25]
Note: I use a modified version of gurk-rs, modified from an old version, so it can be fixed, but I don't think so

https://github.com/boxdot/gurk-rs/blob/master/src/app.rs#L186

Inserting multiple "é" (with other letters) will increase the size of the input in bytes quicker than the cursor, and will result in insertion in previous positions

So the reproduce steps:

+ Open a conversation
+ type 1é1é

Current result:

will be 1éé1 instead of 1é1é

Ps: thx for your work

**Comment by boxdot** [comment]
Thank you for reporting. Fixed in #32
