### ISSUE TITLE
Multiple instances of gurk causes Signal to become de-linked

### ISSUE THREAD

**Issue by josephkerkhof** [boxdot/gurk-rs#261]
Opening multiple instances of gurk causes the Signal authentication to become corrupt.

Steps to reproduce:

1. Open `gurk` with an already linked account.
2. Open another instance of `gurk`. Observe that gurk is displaying a QR code which is prompting you to link your Signal account.
3. Close all instances of `gurk`.
4. Open `gurk`. Observe that your old connection with signal is now lost.

**Comment by gferon** [comment]
Interesting, I'd expect the opening of the sled DB to fail immediately 🤔

**Comment by josephkerkhof** [comment]
I'd be happy to help contribute to a PR resolve this. I was looking at the source code for this and I think it has something to do with [this code](https://github.com/boxdot/gurk-rs/blob/master/src/signal/mod.rs#L47).

I'm a total n00b at rust tho, but willing to learn!

**Comment by boxdot** [comment]
@josephkerkhof Thanks for investigating. I followed this code path deeper. It looks like the migration in presage can't open the sled db, fails and drops the current db. That's why relinking happens. 

@gferon WDYT

**Comment by gferon** [comment]
Definitely a bug, I can fix it.

**Comment by gferon** [comment]
Should be fixed in https://github.com/whisperfish/presage/pull/228
