### ISSUE TITLE
send attachments are not shown when also sending text

### ISSUE THREAD

**Issue by knoxell** [boxdot/gurk-rs#278]
Tested on the current version `0.4.3`, build from the [`gurk-git` package (from the aur)](https://aur.archlinux.org/packages/gurk-git).

## Expected behavior
Sending the message
```
look at these cute cat pics :D
file:///home/user/catpic.0.png
file:///home/user/catpic.1.png
```
results in
```
17:07 user: look at these cute cat pics :D
             <attached: catpic.0.png, catpic.1.png>
```
## Actual behavior
Sending a message like
```
look at these cute cat pics :D
file:///home/user/catpic.0.png
file:///home/user/catpic.1.png
```
results in 
```
17:07 user: look at these cute cat pics :D
```
while sending a message like
```
file:///home/user/catpic.0.png
file:///home/user/catpic.1.png
```
results in 
```
17:07 user:  <attached: catpic.0.png, catpic.1.png>
```

## Additional information

[Here you can find the code responsible for the difference in behavior, between adding text to the attachment or not](https://github.com/boxdot/gurk-rs/blob/a53da028f3f013043d0b4c8b7e6ff2a3cd81a71c/src/signal/impl.rs#L135)  and belongs [to this pull request](https://github.com/boxdot/gurk-rs/pull/231)
I know the code is commented with 
```rust
if has_attachments && message.is_empty() { 
    // TODO: Temporary solution until we start rendering attachments
    ...
}
```
but why only show there are attachments if you don't add text to the message?

Also why not show attachments like it's done with received messages?

## some love
🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒

I just started using the gurk and I love it!

Being able to use signal without the overhead of electronium is awesome and I hope this project and libsignal-service-rs are going to be very long lived!!

I can't wait until viewing or at opening attachments works.

🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒❤️🥒

**Comment by gferon** [comment]
How can we not immediately try to address this issue with such a great use of the 🥒 emojis thank you 🫶🏻!

**Comment by knoxell** [comment]
Hahaha, thank you so much ^^ ❤️
I took the liberty to implement a possible solution myself 🥒🥒🥒 :D
