### ISSUE TITLE
colour of my messages and other people's messages

### ISSUE THREAD

**Issue by anthonyanikos** [boxdot/gurk-rs#285]
Hello, thank you VERY much for your client of signal! 
Can you please tell me if it is possible to add that the colour of my messages and other people's messages should be different?  Your client looks like almost as oldy IRC, but differents colors...

**Comment by boxdot** [comment]
Is the issue in a group chat or in direct message chats?

We use the following colors currently: Red, Green, Yellow, Blue, Magenta, Cyan, Gray. It can happen that they overlap.

**Comment by anthonyanikos** [comment]
Hello, yes, i would. It would be grate! Simple for u, but i could'nt. Dont know rust, hard to understand how to do that.
If you will be able, can u?
All i need - one color for myself text and other color for others, like it was in MIRC. I awlays had green for myselft and pink for other peoples text.
With respect, Anthony

**Comment by boxdot** [comment]
I found a screenshot. I will add a configuration.

**Comment by anthonyanikos** [comment]
Ooh! Thank u very mouch for that possibilitie!!

**Comment by anthonyanikos** [comment]
If u will add this, please notify somehow, if u can.
thank u, before your hands.

**Comment by anthonyanikos** [comment]
Hello, can i ask, at the latest version now is a colored messages?
