### ISSUE TITLE
QR code doesn't work with light color schemes

### ISSUE THREAD

**Issue by 9ary** [boxdot/gurk-rs#288]
I use a light color palette (Selenized white) in my terminals, and I was unable to link my account without switching to a dark variant.

gurk should be able to control the colors more correctly with [true color](https://en.wikipedia.org/wiki/ANSI_escape_code#24-bit) (which many terminals have adopted support for), or the grayscale ramp from the [256 color palette](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit) (which should generally be predictable unless the user has specifically overridden the values).

**Comment by acidvegas** [comment]
I experienced this also. It's ok I guess cause I just had to use a different terminal color scheme for the setup, after that you dont have to worry about it. But was still annoying.

**Comment by boxdot** [comment]
We don't setup terminal colors at all. Instead we rely on `crossterm` backend to do the correct setup for us. I just tested the qr code rendering with the latest crossterm version. The qr code is rendered correctly in `kitty` with Selenized light theme.

Closing this issue for now. In case, you still have it, please post your terminal and theme. I will test it again.
