### ISSUE TITLE
protoc is an undocumented prerequisite

### ISSUE THREAD

**Issue by foxyseta** [boxdot/gurk-rs#289]
`protoc` seems to be a necessary prerequisite for the build. Should this be documented somewhere?

**Comment by boxdot** [comment]
I think we can add it to the readme.

**Comment by foxyseta** [comment]
Same for `pearl` actually, right?

**Comment by boxdot** [comment]
Indeed, we are building openssl because it is used in sqlcipher as crypto library, and for that we need perl. It is unfortunate, but the only way not to require it is to require openssl (or other cryptographic backend being installed). I will add it to the readme.
