### ISSUE TITLE
NixOS, can't add device, Unexpected response: HTTP 409

### ISSUE THREAD

**Issue by AstrantVdev** [boxdot/gurk-rs#303]
I'm under NixOS, and here what I get when I try to link a new device using `gurk` command and after scanning the qr code with signal androïd app :
![image](https://github.com/user-attachments/assets/10686e6b-b805-43aa-bde7-dc7efdc825f8)

Error: failed to provision device: Service error: Unexpected response: HTTP 409

Caused by:
    0: Service error: Unexpected response: HTTP 409
    1: Unexpected response: HTTP 409

**Comment by boxdot** [comment]
This was fixed in #299. New version is not yet released containing this fix. I am working on it.

**Comment by boxdot** [comment]
Version 0.5 containing the fix is released

**Comment by tibequadorian** [comment]
I still have this issue on the latest version

**Comment by GideonWolfe** [comment]
Also seeing this on NixOS 24.11 and `gurk` 0.5.1

**Comment by ffalcon31415** [comment]
I'm also seeing this error on Ubuntu 24.04.2 LTS and gurk 0.6.1
