### ISSUE TITLE
Rust 1.80.0

### ISSUE THREAD

**Issue by devhell** [boxdot/gurk-rs#304]
I'm guessing you're already looking into it, so I'll leave this here, just in case: https://github.com/NixOS/nixpkgs/issues/332957

Thank you very much in advance 🍻

**Comment by devhell** [comment]
Thank you for checking, @boxdot. Thank you, as well, for offering to backport to v0.4, but considering #303 is an issue in v0.4 and v0.5 (I've been getting that issue now too), I don't think it makes sense to put in the effort to backport. I believe it would make more sense to wait until you've released an update that includes the fix for #303.

**Comment by boxdot** [comment]
Version 0.5 containing the fix is released

**Comment by devhell** [comment]
Thank you, @boxdot! :beers:
