### ISSUE TITLE
Error when launching new release.

### ISSUE THREAD

**Issue by SloppyPuppy** [boxdot/gurk-rs#305]
When launching ver 0.5
"
Error: TOML parse error at line 14, column 7
   |
14 | url = ""
   |       ^^
invalid value: string "", expected relative URL without a base
"

If you get this error please delete ~/.config/gurk directory to resolve.

**Comment by boxdot** [comment]
Sorry for breaking the configuration. In 2d28ebfa79c7566ca25b7b3f34f5d814b84efe10, I switched to from string to a stronger type Url. In case, this is too annoying, we can revert this change. Closing for now.
