### ISSUE TITLE
Compilation error E0599 on Raspberry Pi OS

### ISSUE THREAD

**Issue by przem360** [boxdot/gurk-rs#31]
Hi!
I would like to install gurk on my raspberry pi 400 ut process fails like this:

`
cargo install gurk

...

Compiling tui v0.10.0
error[E0599]: no associated item named `MAX` found for type `usize` in the current scope
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.10.0/src/buffer.rs:266:47
    |
266 |         self.set_stringn(x, y, string, usize::MAX, style);
    |                                               ^^^ associated item not found in `usize`
    |
help: you are looking for the module in `std`, not the primitive type
    |
266 |         self.set_stringn(x, y, string, std::usize::MAX, style);
    |                                        ^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `tui`.
warning: build failed, waiting for other jobs to finish...

`

**Comment by cleeyv** [comment]
This was reported upstream in the tui-rs project https://github.com/fdehau/tui-rs/issues/342 and the dev there explained that version 0.10.0 of tui-rs requires version 1.44+ of rustc. Try upgrading your rust and it should resolve the build error.

**Comment by przem360** [comment]
Hi cleeyv, thank you for your suggestion.
Unfortunately my rustc is 1.50.0, I believe it is the newest version.

**Comment by boxdot** [comment]
I just built successfully on my raspberry pi. Here is my environment and hardware:

```
➜  ~ rustc --version
rustc 1.49.0 (e1884a8e3 2020-12-29)
➜  ~ uname -a
Linux raspi 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux
➜  ~ cat /proc/cpuinfo | grep -E 'Revision|Model'
Revision	: d03114
Model		: Raspberry Pi 4 Model B Rev 1.4
```

**Comment by boxdot** [comment]
`tui` was upgraded to 0.14.0 a while ago. Might be that this solves the problem in your environment. Feel free to reopen if the problem persists.
