### ISSUE TITLE
Config and data file creation errors after new install

### ISSUE THREAD

**Issue by cleeyv** [boxdot/gurk-rs#43]
I uninstalled my old gurk and removed all the old config files to test a fresh install. On the initial run of gurk, I got the following output and error (the qr code displayed correctly and I scanned it):
```
[USER@HOST ~]$ gurk
Linking new device with device name: gurk@HOST
Config { data_path: "/home/USER/.local/share/gurk/gurk.data.json", signal_db_path: "/home/USER/.local/share/gurk/signal-db", first_name_only: false, user: User { name: "NAME", phone_number: "+###########" } }
Error: failed to init config file

Caused by:
    No such file or directory (os error 2)
```
This is on Linux. I've been debugging and I think the issue is with this line https://github.com/boxdot/gurk-rs/blob/master/src/config.rs#L42 and that manually creating the directory ~/.config/gurk before the initial run of gurk is a workaround. I'm working on a PR that will hopefully fix the issue.

**Comment by gertjanvanzwieten** [comment]
I'm running into the same issue (fresh install, newly linked device) but for me the proposed workaround is not sufficient. While it results in the creation of a (seemingly correct) configuration file `~/.config/gurk/gurk.toml`, gurk then fails with `Error: failed to load stored data from '/home/USER/.gurk.data.json'`. The error message seems off because when I create `~/.local/share/gurk/gurk.data.json` the output changes, but I don't know how to hand-craft the missing json data.

**Comment by cleeyv** [comment]
I also encountered this second error after I had resolved the first one. The problem seems to be that when there is no gurk.data.json file present anywhere (ie, on a fresh system that does not already have gurk installed) no empty default data file is created. However, one is expected to be there so when gurk tries to load the non-existent file an error is thrown. I'm about to submit a PR for each problem, for creating the config path dirs, and for creating a default data file when none exists.

**Comment by gertjanvanzwieten** [comment]
I just tried these patches and confirm that they solve both issues. (Afterwards I'm faced with an empty channels box but that is certainly a different issue, if any -- I'm new to gurk so not sure yet how it's supposed to function)

**Comment by boxdot** [comment]
@gertjanvanzwieten Thank you for reporting!
@cleeyv Thank you for fixing it!
