### ISSUE TITLE
Encrypt data store

### ISSUE THREAD

**Issue by boxdot** [boxdot/gurk-rs#6]
Messages, contacts, and application state are stored unencrypted. We should encrypt the data on the client. We have to decide, though, which mechanism to use for encryption. I can think of:

1. Use gpg key from configuration
2. Use ssh key from default location or configuration
3. Password on startup

There is some controversy about encryption of the data on the client (see e.g. https://community.signalusers.org/t/why-cant-we-lock-the-desktop-app-with-a-password/1383). However, for a TUI application there is strong use case. Such application can be easily used in multi-user environments, e.g. over ssh, and then messages and contacts are much easier exposed (e.g. to an admin of the machine).

## Note about `signal-cli`:

Since we use signal-cli for communication with the Signal backends, and it stores its own data unecrypted, to provide the full encryption, we would need to replace this backend.

**Comment by cleeyv** [comment]
A related upstream issue was just created for presage: https://github.com/whisperfish/presage/issues/23

**Comment by boxdot** [comment]
* Presage enrypts the stores now
* Gurk migrated to sqlite, so we can use sqlcipher

Signal Android generates a new secret and stores in shared prefs: https://github.com/signalapp/Signal-Android/blob/ebbf8fad4b7224c28d77a9199192b411207008c0/app/src/main/java/org/thoughtcrime/securesms/crypto/DatabaseSecretProvider.java#L75
