### ISSUE TITLE
how do I switch channel keybinding? (noob)

### ISSUE THREAD

**Issue by molleweide** [boxdot/gurk-rs#63]
Hi and thank you so much for putting this program together! I am very excited to try this.
I have also never used rust before.

I want to try gurk-rs but after linking the ui is empty. is this how it is suppose to be?
I am also unsure of what type of keybindings are used in gurk - I am sort of stuck in the `Input` area and I don't know what to do:P Would any of you guys maintaining this project please have time to just point me in the right direction to get
started with this?

EDIT: okay so i figured out how to send message but the issue I am having is that i don't know
how to switch channels and rename them. I have never used rust but I thought this project was a cool way of getting into rust programming. i am going to try to look into the source later. It is amazing to write in the terminal and see it popup in my phone instantly.

**Comment by molleweide** [comment]
oh now I wrote a message to myself on my phone and it poped up under `channels` yay.
So, now I guess my only question is what keybinding do I use to switch channel :D

**Comment by cleeyv** [comment]
The up and down arrow keys navigate through the channels list. You can also use mouse navigation: either by point and click to select a channel, or by scrolling up and down while the mouse cursor is hovering over the channels list.

**Comment by molleweide** [comment]
oh now i get it to work. the reason why it didn't work for me first was probably because I didn't have any conversations.
thanks for replying.
Also does your contact names populate in the channel list or only phone numbers?
