### ISSUE TITLE
Scrolling loops backs to first message

### ISSUE THREAD

**Issue by BennyThadikaran** [boxdot/gurk-rs#68]
When using mouse wheel to scroll the messsages, it does not stop at the last message, instead loops back to the first and continues endless scrolling.

This is problematic, if hundred messages have to be scrolled with a mouse wheel to get to the latest message.

Ideal behavior imho would be to stop scrolling at the last message

**Comment by boxdot** [comment]
Indeed, this makes more sense. Should be also quite easy to implement.

**Comment by boxdot** [comment]
Closing since it was implemented in #72
