### ISSUE TITLE
Document all shortcuts

### ISSUE THREAD

**Issue by boxdot** [boxdot/gurk-rs#71]
Document all shortcuts in the README (or other document linked from README).

As a follow-up, add a screen showing all shortcuts. The screen should be an overlay shown by `shift`+`?` and discarded by `escape`.

**Comment by Sup3Legacy** [comment]
I think `shift` + `?` should not be used as the french (as well as other similar ones) keyboard layout has the `?` character as an uppercase character. So this keybinding would make the overlay pop up each time I type a `?`!

Maybe `alt`+`?` would be a better idea.

**Comment by dbr** [comment]
> I think `shift` + `?` should not be used as the french (as well as other similar ones) keyboard layout has the `?` character as an uppercase character

This is the same on the [US (International) keyboard layout](https://en.wikipedia.org/wiki/British_and_American_keyboards) also - `?` is made with `Shift + /`

`Alt+shift+?` on macOS is shortcut for `¿` key

`Ctrl+?` might work if terminals consistently let you capture that.

`F1` is another option, quite standard key for this - maybe allowing both `F1` and `Ctrl+?` would cover most cases?

**Comment by boxdot** [comment]
Just for reference: https://github.com/ClementTsang/bottom is using `Shift+/ = ?` for the help overview. I think this is what I meant.

**Comment by Sup3Legacy** [comment]
We can now probably close this issue.

**Comment by Sup3Legacy** [comment]
We can now probably close this issue.
