### ISSUE TITLE
Messages from "self" show as "Unknown Name" sender

### ISSUE THREAD

**Issue by chaseadam** [boxdot/gurk-rs#76]
Any message sent by me on any device shows up as "Unknown Name" sender. I have my "Name" set in the Signal App (on phone) and in `gurk.toml`:

```
[user]
name = "<Name>"
phone_number = "+1<10 digit number>"
```

I do note that the `from_id` of the message is not present in `names` JSON sub-document of `gurk.data.json`.

Should a "self" `id` populate automatically?

I am new to rust, so not quite sure how to trace this back yet.

https://github.com/boxdot/gurk-rs/blob/9f994ca13441a262ded74fb192e66df69e8b790b/src/app.rs#L1049

**Comment by boxdot** [comment]
Thank you for reporting this bug. It is a little bit hard for me to reproduce it. Could you please verify if this fix works for you: https://github.com/boxdot/gurk-rs/pull/78? You can install `gurk` from the branch with:

```
cargo install --git https://github.com/boxdot/gurk-rs --branch phone-number-formatting
```

**Comment by gertjanvanzwieten** [comment]
I had exactly the same issue, and just confirmed that the `phone-number-formatting` branch fixes it.
