### ISSUE TITLE
How to keep my phone registered

### ISSUE THREAD

**Issue by oren** [boxdot/gurk-rs#8]
After registering new device
```		
signal-cli -u +xxxxxxxxxxx register
signal-cli -u +xxxxxxxxxxx verify 127-798
```
I see on my signal app (on my phone): device no longer registered. How do I keep the app on my phone working and using this CLI?

**Comment by boxdot** [comment]
I am sorry. The link I provided is wrong. You need to follow instructions at https://github.com/AsamK/signal-cli/wiki/Linking-other-devices-(Provisioning).
