### ISSUE TITLE
Non-persistent notifications

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [boxdot/gurk-rs#94]
Currently notifications are always persistent. It would be nice if they respected the default timeouts set by my notifications daemon (`mako`).

**Comment by boxdot** [comment]
I am using `mako` (with `sway`) with `--default-timeout 10000` and the messages disappear.

**Comment by RagnarGrootKoerkamp** [comment]
Thanks, that fixes it! Another fix is to put `default-timeout=10000` in `~/.config/mako/config`, *outside* of any `[urgency=...]` section. Apparently `notify-send` always uses urgency `normal`, but the ones sent by gurk do not fall into any of the low/normal/high urgency categories.
