### ISSUE TITLE
how do i update gurk? cargo noob quiestion

### ISSUE THREAD

**Issue by molleweide** [boxdot/gurk-rs#98]
Hi,

so i have been doing a couple of searches and i cannot understand how to update gurk to the latest version.
How do i update gurk if i installed it with this command?

```
cargo install --git https://github.com/boxdot/gurk-rs
```

Thanks,

**Comment by boxdot** [comment]
You need to add the extra binary parameter in the end: 

```
cargo install --git https://github.com/boxdot/gurk-rs gurk
```

**Comment by molleweide** [comment]
I will try it. Thanks a lot for quick reply!!
